limit: 50 # number of images to dl from each of train, val, test
class: Flower
type:
  - train
  - validation
  - test
folders:
  img: img
  bbox: img
  metadata: metadata
threads: 10
attributes:
  IsOccluded: False
  IsTruncated: False
  IsDepiction: False
  IsInside: False
  IsGroupOf: null
# do not change these unless u know what you are doing
url:
  - https://storage.googleapis.com/openimages/v6/oidv6-train-annotations-bbox.csv
  - https://storage.googleapis.com/openimages/v5/validation-annotations-bbox.csv
  - https://storage.googleapis.com/openimages/v5/test-annotations-bbox.csv
  - https://storage.googleapis.com/openimages/v5/class-descriptions-boxable.csv
bbox_suffix: annotations-bbox.csv
img_downloader: download.txt