class: Flower
limit: # number of images to dl
  train: 1500
  validation: 400
  test: 200
folders:
  img: img
  bbox: img
  metadata: metadata
threads: 15
attributes:
  IsOccluded: null
  IsTruncated: null
  IsDepiction: False
  IsInside: False
  IsGroupOf: null
# do not change these unless u know what you are doing
url:
  train: https://storage.googleapis.com/openimages/v6/oidv6-train-annotations-bbox.csv
  validation: https://storage.googleapis.com/openimages/v5/validation-annotations-bbox.csv
  test: https://storage.googleapis.com/openimages/v5/test-annotations-bbox.csv
  class: https://storage.googleapis.com/openimages/v5/class-descriptions-boxable.csv
bbox_suffix: annotations-bbox.csv
class_csv: class-descriptions-boxable.csv
img_downloader: download.txt