limit: 500
class: Flower
folders:
  img: img
  bbox: img
  split: split
  metadata: metadata
bbox_suffix: annotations-bbox.csv
img_downloader: download.txt
attributes:
  IsOccluded: False
  IsTruncated: False
  IsDepiction: False
  IsInside: False
  IsGroupOf: null
